configfile: "config/config.yaml"

include: "rules/common.smk"
include: "rules/training.smk"
include: "rules/inference.smk"


rule all:
    input:
        "results/dataset/128/64/True/defined.phastCons.percentile-75_0.05_0.001/train.parquet",
        "results/phylo_dist/0.05",
