version: 2
updates:
  - package-ecosystem: uv
    directory: /
    schedule:
      interval: weekly
    groups:
      python-minor-and-patch:
        update-types:
          - minor
          - patch
    ignore:
      - dependency-name: torch
        update-types: ["version-update:semver-major"]
      - dependency-name: transformers
        update-types: ["version-update:semver-major"]

  - package-ecosystem: pre-commit
    directory: /
    schedule:
      interval: weekly
    groups:
      hooks-minor-and-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions-minor-and-patch:
        update-types:
          - minor
          - patch
