# External data paths - configure these for your environment
external:
  msa_base: /scratch/users/czye/GPN/egpn/analysis/human/egpn/workflow/results/msa/hg38
  fasta_url: http://ftp.ensembl.org/pub/release-107/fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna_sm.primary_assembly.fa.gz

models:
  human:
    - V_small
    - V_medium
    - V_large
    - M_small
    - M_medium
    - M_large
    - P_small
    - P_medium
    - P_large
  human_M_P:
    - M_small
    - M_medium
    - M_large
    - P_small
    - P_medium
    - P_large

gpn_star:
  # Vertebrate (100 species, window=128)
  V_small:
    repo_id: songlab/gpn-star-hg38-v100-25m
    msa_path: multiz100way/100
    window_size: 128
  V_medium:
    repo_id: songlab/gpn-star-hg38-v100-85m
    msa_path: multiz100way/100
    window_size: 128
  V_large:
    repo_id: songlab/gpn-star-hg38-v100-200m
    msa_path: multiz100way/100
    window_size: 128

  # Mammal (447 species, window=256)
  M_small:
    repo_id: songlab/gpn-star-hg38-m447-25m
    msa_path: cactus447way/447
    window_size: 256
  M_medium:
    repo_id: songlab/gpn-star-hg38-m447-85m
    msa_path: cactus447way/447
    window_size: 256
  M_large:
    repo_id: songlab/gpn-star-hg38-m447-200m
    msa_path: cactus447way/447
    window_size: 256

  # Primate (243 species, window=256)
  P_small:
    repo_id: songlab/gpn-star-hg38-p243-25m
    msa_path: cactus447way/243
    window_size: 256
  P_medium:
    repo_id: songlab/gpn-star-hg38-p243-85m
    msa_path: cactus447way/243
    window_size: 256
  P_large:
    repo_id: songlab/gpn-star-hg38-p243-200m
    msa_path: cactus447way/243
    window_size: 256

  dm6:
    repo_id: songlab/gpn-star-dm6-i124-85m
    msa_path: ../dm6/multiz124way/124
    window_size: 128

nuc_dep:
  TH:
    chrom: "11"
    start: 2171682
    end: 2171868
    strand: "-"
  LDLR:
    chrom: "19"
    start: 11089299
    end: 11089425
    strand: "+"
  HBA1:
    chrom: "16"
    start: 176699
    end: 176955
    strand: "+"
  GRIA4:
    chrom: "11"
    start: 105609444
    end: 105609472
    strand: "+"
  drosophila_MSE:
    chrom: "2R"
    start: 9977838
    end: 9977966
    strand: "+"