WANDB_PROJECT=PlantBERT_MLM_CDS python ./run_mlm_custom.py \
    --report_to wandb \
    --run_name ConvNet \
    --do_train \
    --do_eval \
    --train_fasta_path ../../data/mlm/dataset/CDS.parquet \
    --validation_file ../../data/mlm/windows/CDS.test/512/128/seqs.txt \
    --model_name_or_path ./results_512_convnet_finetuning_v2/checkpoint-1000000/ \
    --model_type ConvNet \
    --line_by_line True \
    --window_size 512 \
    --learning_rate 1e-3 \
    --save_strategy steps \
    --save_steps 10000 \
    --max_steps 20000 \
    --evaluation_strategy steps \
    --eval_steps 2000 \
    --dataloader_num_workers 8 \
    --preprocessing_num_workers 8 \
    --warmup_steps 1000 \
    --logging_steps 2000 \
    --output_dir results_CDS_ConvNet \
    --per_device_train_batch_size 256 \
    --per_device_eval_batch_size 256 \
    --gradient_accumulation_steps 1 \
    --fp16 \
    --weight_decay 0.01 \
    --optim adamw_torch \
    --adam_epsilon 1e-4 \
    --seed 42 \
    --prediction_loss_only True \
    --lr_scheduler_type constant_with_warmup \
    --tokenizer_name ../../data/mlm/tokenizer_bare \
