python run_mlm.py \
    --do_train \
    --do_eval \
    --output_dir results \
    --model_type bert \
    --config_overrides vocab_size=1024,hidden_size=512,num_hidden_layers=8,num_attention_heads=8,intermediate_size=2048 \
    --tokenizer_name ./tokenizer_unigram_1019_v2/ \
    --train_file ./lm.train.seqs.txt \
    --max_seq_length 220 \
    --preprocessing_num_workers 12 \
    --line_by_line True \
    --pad_to_max_length True \
    --evaluation_strategy epoch \
    --per_device_train_batch_size 120 \
    --per_device_eval_batch_size 120 \
    --gradient_accumulation_steps 8 \
    --num_train_epochs 100.0 \
    --save_strategy epoch \
    --seed 42 \
    --fp16 \
    --dataloader_num_workers 12 \
    --warmup_ratio 0.01 \
    --save_total_limit 10 \
#    --resume_from_checkpoint ./results/checkpoint-7848
